language: ruby
rvm:
- 2.3.0
before_script:
  - npm install
  - RAILS_ENV=test bundle exec rake db:migrate
script:
  - bundle exec rake test
cache: bundler
addons:
  postgresql: '9.4'
notifications:
  email:
    on_success: never
    on_failure: change